[colors]
background              = "#181818"
foreground              = "#D8D8D8"
cursor                  = "#D8D8D8"
vi-cursor               = "#AA759F"
selection-background    = "#314F78"
selection-foreground    = "#FFFFFF"

black                   = "#181818"
red                     = "#AC4242"
green                   = "#90A959"
yellow                  = "#F4BF75"
blue                    = "#6A9FB5"
magenta                 = "#AA759F"
cyan                    = "#75B5AA"
white                   = "#D8D8D8"

light-black             = "#6B6B6B"
light-red               = "#C55555"
light-green             = "#AAC474"
light-yellow            = "#FECA88"
light-blue              = "#82B8C8"
light-magenta           = "#C28CB8"
light-cyan              = "#93D3C3"
light-white             = "#F8F8F8"
light-foreground        = "#F8F8F8"

dim-black               = "#0F0F0F"
dim-red                 = "#712B2B"
dim-green               = "#5F6F3A"
dim-yellow              = "#A17E4D"
dim-blue                = "#456877"
dim-magenta             = "#704D68"
dim-cyan                = "#4D7770"
dim-white               = "#8E8E8E"
dim-foreground          = "#8E8E8E"
