vo=gpu-next
hwdec=yes
dither-depth=no
video-sync=display-vdrop
macos-render-timer=feedback

use-filedir-conf=yes
fullscreen=yes
autofit-larger=75%x75%
osc=no
osd-bar=no
osd-on-seek=msg
audio-display=no
image-display-duration=inf
screenshot-format=png
screenshot-tag-colorspace=no
screenshot-high-bit-depth=no
screenshot-dir=~/Desktop
watch-later-dir=~~cache/watch_later

alang=ja-JP,en-US,ru-RU,uk-UA
slang=en-US,ru-RU,uk-UA
sub-font-size=45
sub-border-size=2
sub-use-margins=no
sub-scale-with-window=no
sub-ass-vsfilter-blur-compat=no
sub-file-paths=subs
sub-fonts-dir=subs/fonts
