vo=gpu-next
gpu-context=macvk
hwdec=videotoolbox
macos-render-timer=precise
video-sync=display-resample
icc-profile-auto=yes

fullscreen=yes
autofit-larger=75%x75%
osd-bar=no
osd-on-seek=msg
audio-display=no
image-display-duration=inf
screenshot-format=png
screenshot-tag-colorspace=no
screenshot-high-bit-depth=no
screenshot-dir=~/Desktop
watch-later-dir=~~cache/watch_later

alang=ja,en-US,ru,uk
slang=en-US,ru,uk
sub-font-size=45
sub-border-size=2
sub-use-margins=no
sub-scale-with-window=no
sub-file-paths=subs
sub-fonts-dir=subs/fonts
