vo=gpu-next
dither-depth=no
hwdec=videotoolbox
hwdec-codecs=h264,hevc,vp9,prores
macos-render-timer=feedback
video-sync=display-vdrop

alang=ja-JP,en-US,ru-RU,uk-UA
slang=en-US,ru-RU,uk-UA

fullscreen=yes
autofit-larger=75%x75%
audio-display=no
image-display-duration=inf
sub-use-margins=no
sub-file-paths=subs
sub-fonts-dir=subs/fonts
use-filedir-conf=yes
load-auto-profiles=no
ytdl=no
watch-later-dir=~~cache/watch_later

osc=no
osd-bar=no
osd-on-seek=msg
osd-fractions=yes

screenshot-format=png
screenshot-tag-colorspace=no
screenshot-high-bit-depth=no
screenshot-dir=~/Pictures/mpv
